//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuVanLaptoop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TuVanLaptopEntities : DbContext
    {
        public TuVanLaptopEntities()
            : base("name=TuVanLaptopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<GioiTinh> GioiTinhs { get; set; }
        public virtual DbSet<HangLapTop> HangLapTops { get; set; }
        public virtual DbSet<HeDieuHanh> HeDieuHanhs { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<Laptop> Laptops { get; set; }
        public virtual DbSet<Luat> Luats { get; set; }
        public virtual DbSet<MucDich> MucDiches { get; set; }
        public virtual DbSet<NgheNghiep> NgheNghieps { get; set; }
        public virtual DbSet<SuKien> SuKiens { get; set; }
        public virtual DbSet<YeuCauGiaTien> YeuCauGiaTiens { get; set; }
    
        public virtual ObjectResult<Sp_GetSanPham_Result> Sp_GetSanPham(Nullable<decimal> mingiatien, Nullable<decimal> maxgiatien, Nullable<int> hanglaptop, Nullable<int> hedieuhanh)
        {
            var mingiatienParameter = mingiatien.HasValue ?
                new ObjectParameter("mingiatien", mingiatien) :
                new ObjectParameter("mingiatien", typeof(decimal));
    
            var maxgiatienParameter = maxgiatien.HasValue ?
                new ObjectParameter("maxgiatien", maxgiatien) :
                new ObjectParameter("maxgiatien", typeof(decimal));
    
            var hanglaptopParameter = hanglaptop.HasValue ?
                new ObjectParameter("hanglaptop", hanglaptop) :
                new ObjectParameter("hanglaptop", typeof(int));
    
            var hedieuhanhParameter = hedieuhanh.HasValue ?
                new ObjectParameter("hedieuhanh", hedieuhanh) :
                new ObjectParameter("hedieuhanh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetSanPham_Result>("Sp_GetSanPham", mingiatienParameter, maxgiatienParameter, hanglaptopParameter, hedieuhanhParameter);
        }
    }
}
